title: Dan Macpherson
email: brt999@gmail.com
description: >- 
  Data Scientist, Battery Scientist, Athlete, Photographer, Artist.
baseurl: "" 
url: "" 
github_username:  dan-macpherson

theme: minima
header_pages:
  - about.md
