title: Dan Macpherson
email: brt999@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog, where I write about things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dan-macpherson

# Build settings
#mardown: kramdown
#Using custom theme
theme: minima
header_pages:
  - about.md
